package exception;


import java.util.Scanner;
public class ArithmeticExcp{
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int a, b, res;
        System.out.println("Enter the value of a and b");
        a = sc.nextInt();
        b = sc.nextInt();
        try {
            if (b==0) {
                throw new ArithmeticException();
            }
            res = a / b;
            System.out.println("The result is" + res);
        } catch (ArithmeticException e) {
            e.printStackTrace();
        }
    }
}
